// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operations.SyntheticDataGenerator;

#nullable disable

namespace Operations.Migrations
{
    [DbContext(typeof(UdemyDwContext))]
    [Migration("20260615201734_AnalyticStructureUpdate")]
    partial class AnalyticStructureUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimCurso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nivel");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_base");

                    b.Property<decimal>("RatingPromedio")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("rating_promedio");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("IdCurso");

                    b.ToTable("dim_curso");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimDispositivo", b =>
                {
                    b.Property<int>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dispositivo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDispositivo"));

                    b.Property<string>("SistemaOperativo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sistema_operativo");

                    b.Property<string>("TipoDispositivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_dispositivo");

                    b.HasKey("IdDispositivo");

                    b.ToTable("dim_dispositivo");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimEstudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pais");

                    b.HasKey("IdEstudiante");

                    b.ToTable("dim_estudiante");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimPromocion", b =>
                {
                    b.Property<int>("IdPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_promocion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromocion"));

                    b.Property<string>("NombrePromocion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_promocion");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<string>("TipoCampania")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_campania");

                    b.HasKey("IdPromocion");

                    b.ToTable("dim_promocion");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimTiempo", b =>
                {
                    b.Property<int>("IdTiempo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tiempo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTiempo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<int>("Dia")
                        .HasColumnType("int")
                        .HasColumnName("dia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mes");

                    b.Property<int>("Semana")
                        .HasColumnType("int")
                        .HasColumnName("semana");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int")
                        .HasColumnName("trimestre");

                    b.HasKey("IdTiempo");

                    b.ToTable("dim_tiempo");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.EtlConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Update_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("etl_config");
                });

            modelBuilder.Entity("UdemyAnalytics.Models.FactEvaluaciones", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evaluacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<int>("Aprobado")
                        .HasColumnType("int")
                        .HasColumnName("aprobado");

                    b.Property<decimal>("CalificacionObtenida")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("calificacion_obtenida");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("int")
                        .HasColumnName("id_dispositivo");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdTiempo")
                        .HasColumnType("int")
                        .HasColumnName("id_tiempo");

                    b.Property<int>("IntentosRealizados")
                        .HasColumnType("int")
                        .HasColumnName("intentos_realizados");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDispositivo");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdTiempo");

                    b.ToTable("fact_evaluaciones");
                });

            modelBuilder.Entity("UdemyAnalytics.Models.FactInteraccionesProgreso", b =>
                {
                    b.Property<int>("IdInteraccionProgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_interaccion_progreso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInteraccionProgreso"));

                    b.Property<int>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("int")
                        .HasColumnName("id_dispositivo");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdTiempo")
                        .HasColumnType("int")
                        .HasColumnName("id_tiempo");

                    b.Property<int>("ModulosCompletadosCount")
                        .HasColumnType("int")
                        .HasColumnName("modulos_completados_count");

                    b.Property<decimal>("PorcentajeProgresoAcumulado")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_progreso_acumulado");

                    b.Property<int>("TiempoPermanenciaSegundos")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_permanencia_segundos");

                    b.Property<int>("VideosVistos")
                        .HasColumnType("int")
                        .HasColumnName("videos_vistos");

                    b.HasKey("IdInteraccionProgreso");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDispositivo");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdTiempo");

                    b.ToTable("fact_interacciones_progreso");
                });

            modelBuilder.Entity("UdemyAnalytics.Models.FactVentasInscripciones", b =>
                {
                    b.Property<int>("IdVentaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta_inscripcion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentaInscripcion"));

                    b.Property<int>("Completado")
                        .HasColumnType("int")
                        .HasColumnName("completado");

                    b.Property<int?>("DiasParaTerminar")
                        .HasColumnType("int")
                        .HasColumnName("dias_para_terminar");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("int")
                        .HasColumnName("id_dispositivo");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    b.Property<int?>("IdPromocion")
                        .HasColumnType("int")
                        .HasColumnName("id_promocion");

                    b.Property<int>("IdTiempo")
                        .HasColumnType("int")
                        .HasColumnName("id_tiempo");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<decimal>("ProgresoFinalPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progreso_final_porcentaje");

                    b.HasKey("IdVentaInscripcion");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDispositivo");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdPromocion");

                    b.HasIndex("IdTiempo");

                    b.ToTable("fact_ventas_inscripciones");
                });

            modelBuilder.Entity("UdemyAnalytics.Models.FactEvaluaciones", b =>
                {
                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimCurso", "Curso")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimDispositivo", "Dispositivo")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimEstudiante", "Estudiante")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimTiempo", "Tiempo")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdTiempo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Dispositivo");

                    b.Navigation("Estudiante");

                    b.Navigation("Tiempo");
                });

            modelBuilder.Entity("UdemyAnalytics.Models.FactInteraccionesProgreso", b =>
                {
                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimCurso", "Curso")
                        .WithMany("InteraccionesProgresos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimDispositivo", "Dispositivo")
                        .WithMany("InteraccionesProgresos")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimEstudiante", "Estudiante")
                        .WithMany("InteraccionesProgresos")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimTiempo", "Tiempo")
                        .WithMany("InteraccionesProgresos")
                        .HasForeignKey("IdTiempo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Dispositivo");

                    b.Navigation("Estudiante");

                    b.Navigation("Tiempo");
                });

            modelBuilder.Entity("UdemyAnalytics.Models.FactVentasInscripciones", b =>
                {
                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimCurso", "Curso")
                        .WithMany("VentasInscripciones")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimDispositivo", "Dispositivo")
                        .WithMany("VentasInscripciones")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimEstudiante", "Estudiante")
                        .WithMany("VentasInscripciones")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimPromocion", "Promocion")
                        .WithMany("VentasInscripciones")
                        .HasForeignKey("IdPromocion");

                    b.HasOne("Operations.SyntheticDataGenerator.Model.DimTiempo", "Tiempo")
                        .WithMany("VentasInscripciones")
                        .HasForeignKey("IdTiempo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Dispositivo");

                    b.Navigation("Estudiante");

                    b.Navigation("Promocion");

                    b.Navigation("Tiempo");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimCurso", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("InteraccionesProgresos");

                    b.Navigation("VentasInscripciones");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimDispositivo", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("InteraccionesProgresos");

                    b.Navigation("VentasInscripciones");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimEstudiante", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("InteraccionesProgresos");

                    b.Navigation("VentasInscripciones");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimPromocion", b =>
                {
                    b.Navigation("VentasInscripciones");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.DimTiempo", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("InteraccionesProgresos");

                    b.Navigation("VentasInscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
