// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operations;

#nullable disable

namespace Operations.Migrations
{
    [DbContext(typeof(UdemyDwContext))]
    partial class UdemyDwContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.Dim_Curso", b =>
                {
                    b.Property<int>("Id_Curso")
                        .HasColumnType("int");

                    b.Property<int?>("Cantidad_Lecciones")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Curso");

                    b.ToTable("Dim_Curso");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.Dim_Estudiante", b =>
                {
                    b.Property<int>("Id_Estudiante")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Completo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Estudiante");

                    b.ToTable("Dim_Estudiante");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.Dim_Suscripcion", b =>
                {
                    b.Property<int>("Id_Suscripcion")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Suscripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Acceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Suscripcion");

                    b.ToTable("Dim_Suscripcion");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.Dim_Tiempo", b =>
                {
                    b.Property<int>("Id_Tiempo")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<string>("Dia_Semana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Mes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int");

                    b.HasKey("Id_Tiempo");

                    b.ToTable("Dim_Tiempo");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.Etl_Config", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Update_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Etl_Config");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.Fact_Interacciones_Diarias", b =>
                {
                    b.Property<long>("Id_Interaccion_Diaria")
                        .HasColumnType("bigint");

                    b.Property<int>("Cantidad_Reproducciones_Video")
                        .HasColumnType("int");

                    b.Property<int>("Id_Curso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Estudiante")
                        .HasColumnType("int");

                    b.Property<int>("Id_Tiempo")
                        .HasColumnType("int");

                    b.Property<int>("Preguntas_Realizadas")
                        .HasColumnType("int");

                    b.Property<int>("Respuestas_Dadas")
                        .HasColumnType("int");

                    b.Property<decimal>("Tiempo_Visualizacion_Minutos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Interaccion_Diaria");

                    b.ToTable("Fact_Interacciones_Diarias");
                });

            modelBuilder.Entity("Operations.SyntheticDataGenerator.Model.Fact_Rendimiento_Evaluaciones", b =>
                {
                    b.Property<long>("Id_Rendimiento")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Calificacion_Final")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Curso_Finalizado")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Es_Abandono_Temprano")
                        .HasColumnType("tinyint");

                    b.Property<int>("Id_Curso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Estudiante")
                        .HasColumnType("int");

                    b.Property<int>("Id_Suscripcion")
                        .HasColumnType("int");

                    b.Property<int>("Id_Tiempo")
                        .HasColumnType("int");

                    b.Property<decimal>("Progreso_Actual_Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quizzes_Completados")
                        .HasColumnType("int");

                    b.HasKey("Id_Rendimiento");

                    b.ToTable("Fact_Rendimiento_Evaluaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
